### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ChrTall** [matkoch/resharper-fluentassertions#1]
It would be nice if you could add some Documentation to this plugin.
I watched the Jetbrains video some time ago and do not remember exactly what the features of this plugin are.
It is a great idea that Jetbrains supports and showcases these open-source projects :+1:

**Comment by mu88** [comment]
I'd be great if you could provide a short description of how to install this extension 🙂 It doesn't appear within the Extension Manager, even when activating pre-release packages.

**Comment by matkoch** [comment]
I think this was addressed.
