### ISSUE TITLE
Add a way to disable "NUnit assertion can be replaced with FluentAssertions equivalents" or silent it with comment

### ISSUE THREAD

**Issue by Socolin** [matkoch/resharper-fluentassertions#22]
Hello,

Is there a way to disable "NUnit assertion can be replaced with FluentAssertions equivalents"  ? There is some scenario where there is no equivalent with fluentAssertion and I cannot get rid of this warning, it's frustrating.

Assert.Fail("message")

And some custom Assert.That()  like https://github.com/Socolin/Socolin.TestUtils/tree/master/Socolin.TestUtils.JsonComparer.NUnitExtensions

**Comment by matkoch** [comment]
Just on phone, but can't you Alt-Enter => Inspection => Configure Severity ? Remember to choose top-level and not the severity itself to select the settings layer.

**Comment by Socolin** [comment]
![image](https://user-images.githubusercontent.com/539620/170900232-c897411a-e79a-4e21-8f77-0d3103b15be9.png)

https://github.com/matkoch/resharper-fluentassertions/blob/4076f729308ba9e63625bf449ce0d989bb799731/src/dotnet/ReSharperPlugin.FluentAssertions/Highlightings/NUnitAssertMigrationHighlighting.cs

It's a `StaticSeverityHighlighting` (not configurable)

**Comment by matkoch** [comment]
Fixed in `2022.2.0-eap04`.
