### ISSUE TITLE
Rendering is broken in VS 16.9.4

### ISSUE THREAD

**Issue by cd21h** [matkoch/resharper-fluentassertions#4]
Suggestion rendering is broken 

![image](https://user-images.githubusercontent.com/143057/114934744-4f29d280-9e08-11eb-8a93-126e99cdf1bd.png)
![image](https://user-images.githubusercontent.com/143057/114934810-67015680-9e08-11eb-98cc-449e7ce9d194.png)

**Comment by matkoch** [comment]
did you got linked to this repo?

**Comment by matkoch** [comment]
Anyways, should be fixed.
